# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: 6DLabs

# Short description (goes below the title; it will also be used in the RSS feed)
description: Internal stuff

# The directory for category index pages. Change it to something else if
# for example you want links like /categories/category1 instead of /category1
category_dir: /

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
#baseurl: /

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: http://internal.sixdimensions.com

# Exclude system files
exclude: [.gitignore, update.sh]

# Control the number of post per page
paginate: 30